services:
  web:
    image: web
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      - db
    command: > 
      sh -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py populate_data
      python manage.py runserver 0.0.0.0:8080"
  db:
    image: postgres:14-alpine
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always

volumes:
  postgres_data: 
