services:
  web:
    env_file:
      - .env.dev
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      - db
    command: > 
      sh -c "chown -R appuser:appuser /app/staticfiles /app/mediafiles && 
      python manage.py makemigrations --no-input && 
      python manage.py migrate --no-input && 
      python manage.py populate_data && 
      exec su appuser -c 'python manage.py runserver 0.0.0.0:8080'"
  db:
    image: postgres:14-alpine
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always

volumes:
  postgres_data: 
