services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
    command: nginx -g 'daemon off;'
    ports:
      - 80:80
      - 8080:80
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
    restart: always
  web:
    env_file:
      - .env.prod
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=cache
      - POSTGRES_PORT=5432
      - REDIS_PORT=6379
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    expose:
      - "8080"
    depends_on:
      - db
      - cache
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    command: >
      sh -c "chown -R appuser:appuser /app/staticfiles /app/mediafiles && 
      exec su appuser -c '
        python manage.py makemigrations --no-input && 
        python manage.py migrate --no-input && 
        python manage.py collectstatic --no-input && 
        gunicorn --bind 0.0.0.0:8080 config.wsgi:application
      '"
    restart: always
  db:
    image: postgres:14-alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
  cache:
    image: redis:7-alpine
    expose:
     - "6379"
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
