services:
  web:
    image: web
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    command: >
      "gunicorn --bind 0.0.0.0:8080 config.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    restart: always
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 8080:80
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
    restart: always
  db:
    image: postgres:14-alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  static_volume:
  media_volume: