services:
  web:
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      - db
    command: > 
      sh -c "chown -R appuser:appuser /app/staticfiles /app/mediafiles && 
      python manage.py flush --no-input &&
      python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py populate_data &&
      su appuser -c 'gunicorn --bind 0.0.0.0:8080 config.wsgi:application'"
  db:
    image: postgres:14-alpine
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always

volumes:
  postgres_data: 
