# Generated by Django 5.2.8 on 2026-01-06 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='name')),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='color')),
                ('allow_ticket_purchase', models.BooleanField(default=True, verbose_name='allow_ticket_purchase')),
                ('is_running', models.BooleanField(default=True, verbose_name='is_running')),
                ('updated', models.BooleanField(default=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='name')),
                ('updated', models.BooleanField(default=True, verbose_name='updated')),
                ('lines', models.ManyToManyField(blank=True, related_name='stations', to='stations.line')),
                ('neighbours', models.ManyToManyField(blank=True, to='stations.station')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['name'],
            },
        ),
    ]
