# Generated by Django 5.2.8 on 2025-11-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='name')),
                ('color', models.CharField(max_length=7, unique=True, verbose_name='color')),
                ('allow_ticket_purchase', models.BooleanField(default=False, verbose_name='allow_ticket_purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='name')),
                ('footfall', models.PositiveBigIntegerField(default=0, verbose_name='footfall')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.line')),
                ('neighbours', models.ManyToManyField(blank=True, to='stations.station')),
            ],
        ),
    ]
