# Generated by Django 5.2.8 on 2025-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='line',
        ),
        migrations.AddField(
            model_name='station',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='stations', to='stations.line'),
        ),
    ]
