# Generated by Django 5.2.8 on 2025-11-23 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_USE', 'In Use'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_tickets', to='stations.station', verbose_name='start')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_tickets', to='stations.station', verbose_name='stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
