# Generated by Django 5.2.8 on 2025-11-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='raw_status',
        ),
    ]
