# Generated by Django 5.2.8 on 2025-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_remove_station_line_station_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='is_running'),
        ),
    ]
