# Generated by Django 5.2.8 on 2026-01-06 09:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otp', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='price')),
                ('raw_status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_USE', 'In Use'), ('USED', 'Used'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=11, verbose_name='status')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_tickets', to='stations.station', verbose_name='start')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_tickets', to='stations.station', verbose_name='stop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'indexes': [models.Index(fields=['raw_status', 'created_at'], name='tickets_tic_raw_sta_1ccc02_idx'), models.Index(fields=['user', 'raw_status', '-created_at'], name='tickets_tic_user_id_b0cde8_idx')],
            },
        ),
    ]
