# Generated by Django 5.2.8 on 2025-11-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='test_field',
        ),
    ]
